package com.nicoqueijo.android.todolist.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a To-Do item in the application.
 *
 * This data class models a To-Do entity for the database. It is annotated with `@Entity` to
 * indicate that it is a Room entity, and the `id` property is annotated with `@PrimaryKey`
 * to specify it as the primary key, with auto-generation enabled.
 *
 * @property id The unique identifier for the To-Do item. Auto-generated by Room.
 * @property position The position of the To-Do item in a list.
 * @property title The title of the To-Do item.
 * @property description An optional description of the To-Do item.
 * @property isCompleted Indicates whether the To-Do item is completed.
 */
@Entity
data class ToDo(
    @PrimaryKey(autoGenerate = true)
    val id: Int? = null,
    var position: Int = -1,
    val title: String,
    val description: String? = null,
    val isCompleted: Boolean = false,
)
